root: true
env:
  es6: true
  node: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: [tsconfig.json]
  sourceType: 'module'
ignorePatterns:
  - '/build/**/*' # Ignore built files.
plugins:
  - '@typescript-eslint'
  - import
  - jest
rules:
  import/no-unresolved: 0
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  react/jsx-filename-extension: 0
settings:
  import/resolver:
    node:
      extensions: ['.js', 'json', 'cjs', '.ts']
